print ('-' * 35)
print ('Tugas 1 SISOP Kelas-A')
print ('-' * 35)
print ('Nama : Ahmad Wafi Fathurrahman')
print ('NPM : 21083010011')
print ('-' * 35)
print ('notes: ')
print ('-' * 35)
print ('Halo dunia!')
print ('Ini adalah skrip Bash pertamaku di Linux')
